language: haskell-multi-ghc

env:
  - GHCVER=8.0.1 CABALVER=1.24
  - GHCVER=7.10.3 CABALVER=1.22
  - GHCVER=7.8.4  CABALVER=1.18
  - GHCVER=7.6.3  CABALVER=1.18
  - GHCVER=7.4.2  CABALVER=1.18

matrix:
  fast_finish: true

branches:
  only:
    - master
